project:
  type: website

website:
  title: "The Companion book a M1 MODE student should have!"
  navbar:
    left:
      - icon: github
        href: https://github.com/MarieEtienne/MODE_reproduciblescience
        aria-label: GitHub
      - text: "Before the class"
        href: prior_course.qmd
      - text: "Instructions"
        href: instructions.qmd
      - text: "Courses Materials"
        menu:
        - text: Git Intro
          href: https://marieetienne.github.io/reproductibilite/_presentation/english_version.html
        

        
    right:
      - text: Chapter 0 - Introduction
        menu:
        - href: simple_chapter.qmd
        - text: A chapter using R
          href: r_chapter.qmd
        - text: A chapter using Python
          href: python_chapter.qmd
        aria-label: GitHub



format:
  html:
    theme: flatly
    linkcolor: "#c0392b"
    fontcolor: "#057174"
    css: styles.css
    toc: true


    
